name: linting, testing, building

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main  

jobs:
  installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
  build:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: build production project
        run: npm run build:prod
  linting:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
  unit-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: unit testing
        run: npm run test:unit
  regression-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: screenshot testing + storybook
        run: npm run test:ui:ci