name: linting, testing, building

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main  

jobs:
  installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --force
      - name: Save installed modules
        run: |
          mkdir -p installed_modules
          cp -R node_modules installed_modules/
          echo "::set-output name=module-path::installed_modules"

  linting:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore installed modules
        uses: actions/download-artifact@v2
        with:
          name: installed-modules
      - name: linting typescript
        run: npm run lint:ts
        if: always()

  unit-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore installed modules
        uses: actions/download-artifact@v2
        with:
          name: installed-modules
      - name: unit testing
        run: npm run test:unit

  regression-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore installed modules
        uses: actions/download-artifact@v2
        with:
          name: installed-modules
      - name: screenshot testing + storybook
        run: npm run test:ui:ci

  build:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore installed modules
        uses: actions/download-artifact@v2
        with:
          name: installed-modules
      - name: build production project
        run: npm run build:prod

  artifacts:
    runs-on: ubuntu-latest
    needs: [linting, unit-testing, regression-testing, build]
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: installed-modules
          path: ${{ needs.installation.outputs.module-path }}
