name: linting, testing, building

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main  

jobs:
  installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install --force

  linting:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linting
        run: npm run lint

  unit-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: npm run test

  regression-testing:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run regression tests
        run: npm run regression-test

  build:
    runs-on: ubuntu-latest
    needs: installation
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: npm run build
